from enum import Enum

from src.pokemon.types.stat import Stat


class Nature(Enum):
    ADAMANT = (Stat.ATTACK, Stat.SPECIAL_ATTACK)
    BASHFUL = (Stat.SPECIAL_ATTACK, Stat.SPECIAL_ATTACK)
    BOLD = (Stat.DEFENSE, Stat.ATTACK)
    BRAVE = (Stat.ATTACK, Stat.SPEED)
    CALM = (Stat.SPECIAL_DEFENSE, Stat.ATTACK)
    CAREFUL = (Stat.SPECIAL_DEFENSE, Stat.SPECIAL_ATTACK)
    DOCILE = (Stat.DEFENSE, Stat.DEFENSE)
    GENTLE = (Stat.SPECIAL_DEFENSE, Stat.DEFENSE)
    HARDY = (Stat.ATTACK, Stat.ATTACK)
    HASTY = (Stat.SPEED, Stat.DEFENSE)
    IMPISH = (Stat.DEFENSE, Stat.SPECIAL_ATTACK)
    JOLLY = (Stat.SPEED, Stat.SPECIAL_ATTACK)
    LAX = (Stat.DEFENSE, Stat.SPECIAL_DEFENSE)
    LONELY = (Stat.ATTACK, Stat.DEFENSE)
    MILD = (Stat.SPECIAL_ATTACK, Stat.DEFENSE)
    MODEST = (Stat.SPECIAL_ATTACK, Stat.ATTACK)
    NAIVE = (Stat.SPEED, Stat.SPECIAL_DEFENSE)
    NAUGHTY = (Stat.ATTACK, Stat.SPECIAL_DEFENSE)
    QUIET = (Stat.SPECIAL_ATTACK, Stat.SPEED)
    QUIRKY = (Stat.SPECIAL_DEFENSE, Stat.SPECIAL_DEFENSE)
    RASH = (Stat.SPECIAL_ATTACK, Stat.SPECIAL_DEFENSE)
    RELAXED = (Stat.DEFENSE, Stat.SPEED)
    SASSY = (Stat.SPECIAL_DEFENSE, Stat.SPEED)
    SERIOUS = (Stat.SPEED, Stat.SPEED)
    TIMID = (Stat.SPEED, Stat.ATTACK)